// =============================================
// System Roles
// =============================================

const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",

  DIRECTOR: "DIRECTOR",

  ADMIN: "ADMIN",

  PRINCIPAL: "PRINCIPAL",

  VICE_PRINCIPAL: "VICE_PRINCIPAL",

  CONTROLLER_EXAMINATION: "CONTROLLER_EXAMINATION",

  DISCIPLINE_INCHARGE: "DISCIPLINE_INCHARGE",

  HR_MANAGER: "HR_MANAGER",

  ACCOUNTS_OFFICER: "ACCOUNTS_OFFICER",

  CLASS_INCHARGE: "CLASS_INCHARGE",

  SUBJECT_TEACHER: "SUBJECT_TEACHER",

  STUDENT: "STUDENT",

  PARENT: "PARENT",

  LIBRARIAN: "LIBRARIAN",

  RECEPTIONIST: "RECEPTIONIST",

  TRANSPORT_MANAGER: "TRANSPORT_MANAGER",

  HOSTEL_WARDEN: "HOSTEL_WARDEN"
};

export default ROLES;